# Generated by Django 2.2.5 on 2019-09-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/man.png', null=True, upload_to='profile_pics'),
        ),
    ]
