# Generated by Django 2.2.5 on 2019-10-04 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_skills'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='skills',
            new_name='Skill',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='skill',
            new_name='value',
        ),
    ]
