# Generated by Django 2.2.5 on 2019-10-04 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_themes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Themes',
            new_name='Theme',
        ),
    ]
