# Generated by Django 2.2.5 on 2019-10-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_auto_20191004_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggested_theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField()),
            ],
        ),
    ]
